only_boards:
  - arduino:avr:uno
library_archives:
  - autowp-mcp2515=https://github.com/autowp/arduino-mcp2515/archive/v1.1.0.tar.gz=0
  - CAN Adafruit Fork=https://github.com/adafruit/arduino-CAN/archive/1.2.1.tar.gz=0