only_boards:
  - arduino:avr:uno
skip_boards:
  - esp8266:esp8266:huzzah
library_archives:
  - autowp-mcp2515=https://github.com/autowp/arduino-mcp2515/archive/v1.1.0.tar.gz=0
  - CAN=https://github.com/sandeepmistry/arduino-CAN/archive/0.3.1.tar.gz=0